import { useCallback, useEffect, useMemo, useState } from 'react';
import { ApiError, apiRequest } from '../../shared/api/client';
import './leads.css';

type Status = 'NEW'|'ENRICHING'|'QUALIFIED'|'TO_CONTACT'|'CONTACTED'|'REPLIED'|'MEETING'|'OPPORTUNITY'|'WON'|'LOST';
type Lead = { id: string; businessName: string; category: string; subcategory?: string|null; description?: string|null; website: string; domain: string; city: string; provinceState: string; country: string; address?: string|null; googleMapsUrl?: string|null; instagramUrl?: string|null; linkedinUrl?: string|null; phone?: string|null; contactName?: string|null; contactRole?: string|null; contactEmail?: string|null; source: string; sourceReference?: string|null; score?: number|null; recommendedOffer?: string|null; recommendedDemo?: string|null; status: Status; notes?: string|null; lastContactAt?: number|null; nextActionAt?: number|null; createdAt: number; updatedAt: number };
type Job = { id: string; type: string; status: string; progress: number; total: number; processed: number; succeeded: number; failed: number; metadata?: string|null; error?: string|null; createdAt: number; updatedAt?: number; startedAt?: number|null; finishedAt?: number|null };
type FinderCategory = { value: string; label: string };
type Response = { items: Lead[]; total: number; kpis: Record<string, number>; jobs: Job[] };
const statusLabels: Record<Status, string> = { NEW:'Nuevo', ENRICHING:'Enriqueciendo', QUALIFIED:'Calificado', TO_CONTACT:'Contactar', CONTACTED:'Contactado', REPLIED:'Respondió', MEETING:'Reunión', OPPORTUNITY:'Oportunidad', WON:'Ganado', LOST:'Perdido' };
const statuses = Object.keys(statusLabels) as Status[];
const jobStatusLabels: Record<string, string> = { QUEUED:'En cola', RUNNING:'Ejecutando', COMPLETED:'Completado', FAILED:'Fallido', CANCELLED:'Cancelado' };
const jobTypeLabels: Record<string, string> = { FINDER:'Finder', ENRICHER:'Enricher', SCORING:'Scoring', OUTREACH_PREPARATION:'Preparar contacto' };
const jobLabel = (job: Job) => { if (job.type !== 'FINDER' || !job.metadata) return jobTypeLabels[job.type] ?? job.type; try { const mode = JSON.parse(job.metadata).mode; return mode === 'external_dry_run' ? 'Finder externo' : mode === 'external_persist_test' ? 'Finder real' : mode === 'external_persist' ? 'Finder' : jobTypeLabels[job.type] ?? job.type; } catch { return jobTypeLabels[job.type] ?? job.type; } };
const jobFinderDetails = (job: Job) => { if (job.type !== 'FINDER' || !job.metadata) return ''; try { const metadata = JSON.parse(job.metadata); const search = metadata.search; const persist = metadata.persist; const parts = [search?.category, search?.location].filter(Boolean).join(' · '); const metrics = persist ? ` · Creados: ${persist.leadsCreated ?? 0} · Duplicados: ${persist.duplicates ?? 0} · Analizados: ${persist.candidatesSeen ?? 0}` : ''; return parts + metrics; } catch { return ''; } };
const date = (value?: number|null) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium' }).format(new Date(value)) : '—';
const place = (lead: Lead) => [lead.city, lead.provinceState].filter(Boolean).join(', ') || '—';
const duration = (job: Job) => { const end = job.finishedAt ?? (job.status === 'RUNNING' ? Date.now() : job.createdAt); const start = job.startedAt ?? job.createdAt; const seconds = Math.max(0, Math.round((end - start) / 1000)); return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`; };

export function LeadsPage({ org, canEdit }: { org: string; canEdit: boolean }) {
  const [data, setData] = useState<Response>(); const [selected, setSelected] = useState<Lead>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creatingJob, setCreatingJob] = useState(false); const [creatingExternalJob, setCreatingExternalJob] = useState(false); const [creatingPersistJob, setCreatingPersistJob] = useState(false); const [finderOpen, setFinderOpen] = useState(false); const [finderCategories, setFinderCategories] = useState<FinderCategory[]>([]); const [finderCategory, setFinderCategory] = useState('inmobiliaria'); const [finderLocation, setFinderLocation] = useState(''); const [finderLimit, setFinderLimit] = useState('10');
  const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [status, setStatus] = useState(''); const [minScore, setMinScore] = useState(''); const [offer, setOffer] = useState('');
  const load = useCallback(async () => { if (!org) return; setLoading(true); setError(''); try { const query = new URLSearchParams(); if (search) query.set('search', search); if (category) query.set('category', category); if (status) query.set('status', status); if (minScore) query.set('minScore', minScore); if (offer) query.set('offer', offer); setData(await apiRequest<Response>(`/leads?${query}`, org)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'No se pudieron cargar los leads.'); } finally { setLoading(false); } }, [org, search, category, status, minScore, offer]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 160); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (!org) return; void apiRequest<{ items: FinderCategory[] }>('/leads/finder/categories', org).then((result) => { setFinderCategories(result.items); if (result.items.length && !result.items.some((item) => item.value === finderCategory)) setFinderCategory(result.items[0].value); }).catch(() => setFinderCategories([])); }, [org]);
  const activeJobs = (data?.jobs ?? []).some((job) => job.status === 'QUEUED' || job.status === 'RUNNING');
  useEffect(() => { if (!activeJobs) return; const timer = window.setInterval(() => void load(), 2500); return () => window.clearInterval(timer); }, [activeJobs, load]);
  const categories = useMemo(() => [...new Set((data?.items ?? []).map((item) => item.category))].sort(), [data]); const offers = useMemo(() => [...new Set((data?.items ?? []).map((item) => item.recommendedOffer).filter(Boolean))] as string[], [data]);
  async function updateStatus(next: Status) { if (!selected || !canEdit) return; try { const fresh = await apiRequest<Lead>(`/leads/${selected.id}`, org, { method: 'PATCH', body: JSON.stringify({ status: next }) }); setSelected(fresh); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'No se pudo actualizar el estado.'); } }
  async function createTestJob() { if (!canEdit || creatingJob) return; setCreatingJob(true); setError(''); try { await apiRequest<Job>('/leads/jobs', org, { method: 'POST', body: JSON.stringify({ type: 'FINDER', metadata: { mode: 'test', category: 'TEST', location: 'TEST', limit: 25 } }) }); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'No se pudo iniciar el proceso de prueba.'); } finally { setCreatingJob(false); } }
  async function createExternalFinderJob() { if (!canEdit || creatingExternalJob) return; setCreatingExternalJob(true); setError(''); try { await apiRequest<Job>('/leads/jobs', org, { method: 'POST', body: JSON.stringify({ type: 'FINDER', metadata: { mode: 'external_dry_run', category: 'inmobiliaria', location: 'Villa Carlos Paz, Córdoba', limit: 1 } }) }); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'No se pudo iniciar el Finder externo.'); } finally { setCreatingExternalJob(false); } }
  async function createPersistFinderJob() { if (!canEdit || creatingPersistJob || !finderLocation.trim() || ![5, 10, 25].includes(Number(finderLimit))) return; setCreatingPersistJob(true); setError(''); try { await apiRequest<Job>('/leads/jobs', org, { method: 'POST', body: JSON.stringify({ type: 'FINDER', metadata: { mode: 'external_persist', category: finderCategory, location: finderLocation.trim(), limit: Number(finderLimit) } }) }); setFinderOpen(false); setFinderLocation(''); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'No se pudo iniciar la búsqueda de Leads.'); } finally { setCreatingPersistJob(false); } }
  async function cancelJob(job: Job) { if (!canEdit || (job.status !== 'QUEUED' && job.status !== 'RUNNING')) return; try { await apiRequest<Job>(`/leads/jobs/${job.id}/cancel`, org, { method: 'POST' }); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'No se pudo cancelar el proceso.'); } }
  const kpis = data?.kpis ?? {};
  return <main className="page leads-page">
    <div className="page-heading leads-heading"><div><p className="eyebrow">PROSPECCIÓN COMERCIAL</p><h1>Leads</h1><p className="page-description">Organizá oportunidades desde el primer descubrimiento hasta una reunión comercial.</p></div><div className="leads-heading-actions">{canEdit && <><button className="button button-primary" type="button" onClick={() => setFinderOpen(true)} disabled={creatingJob || creatingExternalJob || creatingPersistJob}>Buscar Leads</button><details className="leads-diagnostics"><summary>Diagnóstico</summary><div><button className="button button-secondary" type="button" onClick={() => void createTestJob()} disabled={creatingJob || creatingExternalJob || creatingPersistJob}>{creatingJob ? 'Iniciando…' : 'Probar motor de procesos'}</button><button className="button button-quiet" type="button" onClick={() => void createExternalFinderJob()} disabled={creatingJob || creatingExternalJob || creatingPersistJob}>{creatingExternalJob ? 'Iniciando Finder…' : 'Probar Finder externo'}</button></div></details></>}<span className="leads-stage-note">Etapa 3E · Buscar Leads</span></div></div>
    <section className="leads-kpis" aria-label="Resumen de leads">{[['total','Leads totales'],['new','Nuevos'],['qualified','Calificados'],['toContact','Para contactar'],['replied','Respondieron'],['meetings','Reuniones'],['opportunities','Oportunidades']].map(([key, label]) => <div className="lead-kpi" key={key}><span>{label}</span><strong>{kpis[key] ?? 0}</strong></div>)}</section>
    <section className="leads-toolbar" aria-label="Filtros de leads"><label className="leads-search">Buscar<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Empresa, dominio o contacto" /></label><label>Categoría<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Todas</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Estado<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos</option>{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label><label>Score mínimo<input type="number" min="0" max="100" value={minScore} onChange={(e) => setMinScore(e.target.value)} placeholder="—" /></label><label>Oferta<select value={offer} onChange={(e) => setOffer(e.target.value)}><option value="">Todas</option>{offers.map((item) => <option key={item}>{item}</option>)}</select></label></section>
    {error && <p className="error" role="alert">{error}</p>}
    {loading ? <div className="loading-state"><span className="loading-mark" />Cargando leads…</div> : !data?.items.length ? <div className="empty leads-empty"><h2>{data?.total ? 'No hay resultados para estos filtros' : 'Todavía no hay leads'}</h2><p>{data?.total ? 'Probá quitando algún filtro para ampliar la búsqueda.' : 'Los leads incorporados en futuras etapas aparecerán en esta vista.'}</p></div> : <section className="leads-table-card"><div className="leads-table-wrap"><table className="leads-table"><caption className="sr-only">Leads de la organización</caption><thead><tr><th>Empresa</th><th>Categoría</th><th>Ubicación</th><th>Score</th><th>Oferta</th><th>Estado</th><th>Contacto</th><th>Próxima acción</th><th>Creado</th></tr></thead><tbody>{data.items.map((lead) => <tr key={lead.id} onClick={() => setSelected(lead)} tabIndex={0} onKeyDown={(e) => { if (e.key === 'Enter') setSelected(lead); }}><td><strong>{lead.businessName}</strong><small>{lead.domain}</small></td><td>{lead.category}</td><td>{place(lead)}</td><td><span className={`lead-score ${lead.score !== null && lead.score !== undefined && lead.score >= 80 ? 'high' : ''}`}>{lead.score ?? '—'}</span></td><td>{lead.recommendedOffer || '—'}</td><td><span className={`lead-status status-${lead.status.toLowerCase()}`}>{statusLabels[lead.status]}</span></td><td>{lead.contactName || lead.contactEmail || 'Sin contacto'}</td><td>{date(lead.nextActionAt)}</td><td>{date(lead.createdAt)}</td></tr>)}</tbody></table></div><footer className="leads-table-footer">{data.total} {data.total === 1 ? 'lead encontrado' : 'leads encontrados'}<span>Seleccioná una fila para ver el detalle</span></footer></section>}
    <section className="leads-processes" aria-label="Procesos de Leads"><div className="leads-processes-heading"><div><p className="eyebrow">OPERACIÓN</p><h2>Procesos</h2></div><span>{activeJobs ? 'Actualizando cada 2,5 s' : 'Sin procesos activos'}</span></div>{!data?.jobs.length ? <p className="leads-process-empty">Los procesos ejecutados aparecerán aquí. Las pruebas internas y el Finder externo dry-run no crean leads reales.</p> : <div className="leads-job-list">{data.jobs.map((job) => <article className="leads-job" key={job.id}><div className="leads-job-main"><div><strong>{jobLabel(job)}</strong><span className={`job-status job-${job.status.toLowerCase()}`}>{jobStatusLabels[job.status] ?? job.status}</span></div><small>{jobFinderDetails(job) || date(job.createdAt)} · Duración {duration(job)}</small></div><div className="leads-job-progress"><div className="leads-job-progress-meta"><span>{job.processed} / {job.total}</span><strong>{job.progress}%</strong></div><div className="progress-track"><span style={{ width: `${job.progress}%` }} /></div><small>Correctos: {job.succeeded} · Errores: {job.failed}{job.error ? ` · ${job.error}` : ''}</small></div>{(job.status === 'QUEUED' || job.status === 'RUNNING') && canEdit && <button className="button button-quiet" type="button" onClick={() => void cancelJob(job)}>Cancelar</button>}</article>)}</div>}</section>
    {finderOpen && <div className="modal-backdrop" role="presentation" onClick={() => setFinderOpen(false)}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="finder-dialog-title" onClick={(event) => event.stopPropagation()}><div className="lead-drawer-head"><div><p className="eyebrow">FINDER</p><h2 id="finder-dialog-title">Buscar Leads</h2></div><button className="button button-quiet" type="button" onClick={() => setFinderOpen(false)}>Cerrar</button></div><form onSubmit={(event) => { event.preventDefault(); void createPersistFinderJob(); }}><label>Categoría<select value={finderCategory} onChange={(event) => setFinderCategory(event.target.value)} required>{finderCategories.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Ubicación<input value={finderLocation} onChange={(event) => setFinderLocation(event.target.value)} placeholder="Villa Carlos Paz, Córdoba" required minLength={2} /></label><label>Cantidad<select value={finderLimit} onChange={(event) => setFinderLimit(event.target.value)}><option value="5">5 Leads nuevos</option><option value="10">10 Leads nuevos</option><option value="25">25 Leads nuevos</option></select></label><p>Los duplicados no consumen el objetivo. El buscador se detiene al alcanzar la cantidad solicitada o el límite seguro de exploración.</p><button className="button button-primary" type="submit" disabled={creatingPersistJob || !finderLocation.trim()}>{creatingPersistJob ? 'Creando búsqueda…' : 'Crear búsqueda'}</button></form></section></div>}
    {selected && <aside className="lead-drawer" aria-label="Detalle del lead"><div className="lead-drawer-head"><div><p className="eyebrow">DETALLE DEL LEAD</p><h2>{selected.businessName}</h2><p>{place(selected)} · {selected.domain}</p></div><button className="button button-quiet" onClick={() => setSelected(undefined)} aria-label="Cerrar detalle">Cerrar</button></div><div className="lead-drawer-body"><section><h3>Empresa</h3><dl><dt>Categoría</dt><dd>{selected.category}{selected.subcategory ? ` · ${selected.subcategory}` : ''}</dd><dt>Descripción</dt><dd>{selected.description || '—'}</dd><dt>Fuente</dt><dd>{selected.source}</dd></dl></section><section><h3>Contacto</h3><dl><dt>Nombre</dt><dd>{selected.contactName || '—'}{selected.contactRole ? ` · ${selected.contactRole}` : ''}</dd><dt>Email</dt><dd>{selected.contactEmail || '—'}</dd><dt>Teléfono</dt><dd>{selected.phone || '—'}</dd><dt>LinkedIn</dt><dd>{selected.linkedinUrl ? <a href={selected.linkedinUrl} target="_blank" rel="noreferrer">Abrir perfil ↗</a> : '—'}</dd></dl></section><section><h3>Presencia digital</h3><div className="lead-links">{[['Web', selected.website],['Google Maps', selected.googleMapsUrl],['Instagram', selected.instagramUrl],['LinkedIn', selected.linkedinUrl]].map(([label, url]) => url ? <a key={label} href={url} target="_blank" rel="noreferrer">{label} ↗</a> : null)}</div></section><section><h3>Comercial</h3><label>Estado<select disabled={!canEdit} value={selected.status} onChange={(e) => void updateStatus(e.target.value as Status)}>{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label><dl><dt>Score</dt><dd>{selected.score ?? 'Sin calificar'}</dd><dt>Oferta recomendada</dt><dd>{selected.recommendedOffer || '—'}</dd><dt>Demo recomendada</dt><dd>{selected.recommendedDemo || '—'}</dd><dt>Último contacto</dt><dd>{date(selected.lastContactAt)}</dd><dt>Próxima acción</dt><dd>{date(selected.nextActionAt)}</dd></dl></section><section><h3>Notas</h3><p className="lead-notes">{selected.notes || 'Sin notas todavía.'}</p></section><section className="lead-activity"><h3>Procesos</h3><p>Los procesos automáticos aparecerán aquí en próximas etapas.</p></section></div></aside>}
  </main>;
}
