import { useEffect, useState } from 'react';
import { experiencesApi, type ExperienceSpin } from '../api';

type Props = { experienceId: string; organizationId: string; prizes: Array<{ id: string; name: string }> };
function shortId(id: string) { return `${id.slice(0, 8)}…`; }
function dateLabel(value: string) { return new Date(value).toLocaleString('es-AR'); }

export function SpinHistory({ experienceId, organizationId, prizes }: Props) {
  const [items, setItems] = useState<ExperienceSpin[]>([]); const [outcome, setOutcome] = useState(''); const [prizeId, setPrizeId] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [offset, setOffset] = useState(0); const [nextOffset, setNextOffset] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { setLoading(true); setError(false); experiencesApi.spins(experienceId, organizationId, { limit: 25, offset, outcome: outcome || undefined, prizeId: prizeId || undefined, from: from || undefined, to: to || undefined }).then((result) => { setItems(result.items); setNextOffset(result.pagination.nextOffset); }).catch(() => setError(true)).finally(() => setLoading(false)); }, [experienceId, organizationId, offset, outcome, prizeId, from, to]);
  const filter = (setter: (value: string) => void, value: string) => { setter(value); setOffset(0); };
  return <section className="card spin-history"><h2>Historial de giros</h2><p className="field-help">Este historial registra los resultados confirmados por el servidor.</p><div className="filters"><label>Resultado<select value={outcome} onChange={(e) => filter(setOutcome, e.target.value)}><option value="">Todos</option><option value="prize">Premio</option><option value="no_prize">Sin premio</option></select></label><label>Premio<select value={prizeId} onChange={(e) => filter(setPrizeId, e.target.value)}><option value="">Todos</option>{prizes.map((prize) => <option key={prize.id} value={prize.id}>{prize.name}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={(e) => filter(setFrom, e.target.value)} /></label><label>Hasta<input type="date" value={to} onChange={(e) => filter(setTo, e.target.value)} /></label></div>{loading ? <p>Cargando historial…</p> : error ? <p className="error">No se pudo cargar el historial.</p> : items.length === 0 ? <p>Todavía no hay giros registrados para esta experiencia.</p> : <><div className="spin-history-table" role="table"><div className="spin-history-row spin-history-head" role="row"><span>Fecha</span><span>Resultado</span><span>Premio</span><span>Segmento</span><span>Spin ID</span></div>{items.map((item) => <div className="spin-history-row" role="row" key={item.id}><span>{dateLabel(item.createdAt)}</span><span>{item.outcomeType === 'prize' ? 'Premio' : 'Sin premio'}</span><span>{item.prizeId ? prizes.find((prize) => prize.id === item.prizeId)?.name ?? item.prizeId : '—'}</span><span>{item.segmentIndex + 1}</span><span title={item.id}>{shortId(item.id)}</span></div>)}</div><div className="pagination"><button className="secondary" disabled={!offset || loading} onClick={() => setOffset(Math.max(0, offset - 25))}>Anterior</button><button className="secondary" disabled={nextOffset === null || loading} onClick={() => setOffset(nextOffset ?? offset)}>Siguiente</button></div></>}</section>;
}
