import { Hono } from 'hono'; import type { Context } from 'hono'; import { requireAuth,requireOrganization } from '../auth/middleware'; import type { Env } from '../index';
type Range='24h'|'7d'|'30d'|'all';type Metric='users'|'events'|'games'|'prizes';type Dimension='game'|'prize'|'result';type Vars={user:{id:string;email:string;name:string;platformRole:string};sessionId:string;organization:{id:string;name:string;slug:string;role:string}};
export const analyticsRoutes=new Hono<{Bindings:Env;Variables:Vars}>();analyticsRoutes.use('*',requireAuth,requireOrganization);
const rangeOf=(x:string|undefined):Range=>x==='24h'||x==='7d'||x==='30d'||x==='all'?x:'7d';const sinceOf=(r:Range)=>r==='all'?0:Date.now()-({'24h':86400000,'7d':604800000,'30d':2592000000}[r]);
async function scope(c:Context<{Bindings:Env;Variables:Vars}>){const q=c.req.query();const range=rangeOf(q.range);const org=c.get('organization');const values:(string|number)[]=[org.id,sinceOf(range)];let where='organization_id=? AND occurred_at>=?';if(q.projectId){const p=await c.env.DB.prepare('SELECT id FROM projects WHERE id=? AND organization_id=?').bind(q.projectId,org.id).first();if(!p)throw new Response('Not found',{status:404});where+=' AND project_id=?';values.push(q.projectId)}if(q.applicationId){const a=await c.env.DB.prepare('SELECT id FROM applications WHERE id=? AND organization_id=?'+(q.projectId?' AND project_id=?':'')).bind(...(q.projectId?[q.applicationId,org.id,q.projectId]:[q.applicationId,org.id])).first();if(!a)throw new Response('Not found',{status:404});where+=' AND application_id=?';values.push(q.applicationId)}return{q,range,where,values,org};}
const run=(c:Context<{Bindings:Env;Variables:Vars}>,sql:string,values:(string|number)[])=>c.env.DB.prepare(sql).bind(...values).all<{event_name:string;n:number}>();
analyticsRoutes.get('/summary',async c=>{const s=await scope(c);const rows=await run(c,`SELECT event_name,COUNT(*) n FROM events WHERE ${s.where} GROUP BY event_name`,s.values) as {results:{event_name:string;n:number}[]};const count=(n:string)=>rows.results.find(x=>x.event_name===n)?.n??0;const u=await c.env.DB.prepare(`SELECT COUNT(DISTINCT anonymous_user_id) n FROM events WHERE ${s.where}`).bind(...s.values).first<{n:number}>();const se=await c.env.DB.prepare(`SELECT COUNT(DISTINCT session_id) n FROM events WHERE ${s.where}`).bind(...s.values).first<{n:number}>();const started=count('game_started');return c.json({range:s.range,totals:{uniqueUsers:u?.n??0,sessions:se?.n??0,appOpens:count('app_opened'),gamesStarted:started,gamesFinished:count('game_finished'),prizesWon:count('prize_won'),prizesClaimed:count('prize_claimed')},rates:{completion:started?count('game_finished')/started:0,prizeConversion:started?count('prize_won')/started:0}})});
analyticsRoutes.get('/activity',async c=>{const s=await scope(c);const limit=Math.min(Number(s.q.limit)||20,50);return c.json((await run(c,`SELECT occurred_at occurredAt,event_name event,anonymous_user_id anonymousUserId,properties FROM events WHERE ${s.where} ORDER BY occurred_at DESC LIMIT ?`,[...s.values,limit])).results)});
analyticsRoutes.get('/breakdown',async c=>{const s=await scope(c);const d=s.q.dimension as Dimension|undefined;if(d!=='game'&&d!=='prize'&&d!=='result')return c.json({error:{code:'BAD_REQUEST',message:'Invalid dimension'}},400);const rows=await c.env.DB.prepare(`SELECT properties FROM events WHERE ${s.where} AND properties IS NOT NULL`).bind(...s.values).all<{properties:string}>();const m=new Map<string,number>();for(const row of rows.results){try{const v=(JSON.parse(row.properties) as Record<string,unknown>)[d];if(typeof v==='string')m.set(v,(m.get(v)??0)+1)}catch{continue;}}return c.json({dimension:d,items:[...m].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value}))})});
analyticsRoutes.get('/recurrence',async c=>{const s=await scope(c);const rows=await c.env.DB.prepare(`SELECT anonymous_user_id userId,COUNT(*) n FROM events WHERE ${s.where} AND event_name=? AND anonymous_user_id IS NOT NULL GROUP BY anonymous_user_id`).bind(...s.values,'game_finished').all<{userId:string;n:number}>();const result={once:0,twice:0,threeOrMore:0};for(const row of rows.results){if(row.n===1)result.once++;else if(row.n===2)result.twice++;else result.threeOrMore++;}return c.json(result)});
analyticsRoutes.get('/timeseries',async c=>{const s=await scope(c);const metric=s.q.metric as Metric|undefined;if(metric!=='users'&&metric!=='events'&&metric!=='games'&&metric!=='prizes')return c.json({error:{code:'BAD_REQUEST',message:'Invalid metric'}},400);const size=s.range==='24h'?3600000:86400000;const rows=await c.env.DB.prepare(`SELECT occurred_at occurredAt,event_name event,anonymous_user_id userId FROM events WHERE ${s.where} ORDER BY occurred_at`).bind(...s.values).all<{occurredAt:number;event:string;userId:string|null}>();const p=new Map<number,Set<string>|number>();for(const row of rows.results){const b=Math.floor(row.occurredAt/size)*size;const old=p.get(b);if(metric==='users'){if(old instanceof Set)old.add(row.userId??'');else p.set(b,new Set(row.userId?[row.userId]:[]));}else{const value=metric==='events'?1:metric==='games'&&['game_started','game_finished'].includes(row.event)?1:metric==='prizes'&&['prize_won','prize_claimed'].includes(row.event)?1:0;p.set(b,(typeof old==='number'?old:0)+value);}}return c.json({metric,range:s.range,interval:s.range==='24h'?'hour':'day',points:[...p].sort((a,b)=>a[0]-b[0]).map(([timestamp,value])=>({timestamp,value:value instanceof Set?value.size:value}))})});
