import { useEffect, useState } from 'react';
import { formatMoneyFromMinor, parseMoneyToMinor } from '@corsteno/types';
import { COMMERCIAL_FEATURE_LABELS, COMMERCIAL_PLAN_DEFINITIONS, type CommercialPlanCode } from '@corsteno/types';
import { commercialApi, type Plan } from '../api';

function price(plan: Plan) { return plan.priceAmountMinor === 0 ? 'Precio pendiente' : formatMoneyFromMinor(plan.priceAmountMinor, plan.currency); }
function interval(plan: Plan) { return plan.billingInterval === 'one_time' ? `Pago único · ${plan.includedAccessDays ?? 0} días` : `${plan.billingInterval === 'monthly' ? 'Mensual' : 'Anual'}${plan.billingIntervalCount > 1 ? ` · ${plan.billingIntervalCount} períodos` : ''}`; }

export function CommercialPage({ org, canManageCatalog = false }: { org: string; canManageCatalog?: boolean }) {
  const [plans, setPlans] = useState<Plan[]>([]), [error, setError] = useState(''), [editing, setEditing] = useState<string | null>(null), [saving, setSaving] = useState(false);
  async function load() { try { setPlans(await (canManageCatalog ? commercialApi.catalog(org) : commercialApi.plans(org))); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { if (org) void load(); }, [org, canManageCatalog]);
  async function save(plan: Plan, form: HTMLFormElement) { const data = new FormData(form); const pricingMode = String(data.get('pricingMode') ?? 'unconfigured'); const amount = pricingMode === 'free' ? 0 : parseMoneyToMinor(String(data.get('amount') ?? '')); if (amount === null) { setError('Ingresá un importe válido con hasta dos decimales.'); return; } setSaving(true); setError(''); try { await commercialApi.updatePlan(plan.id, org, { name: String(data.get('name') ?? ''), description: String(data.get('description') ?? ''), price_amount_minor: amount, pricing_mode: pricingMode, currency: String(data.get('currency') ?? ''), available_for_sale: data.get('available') === 'on' ? 1 : 0, active: data.get('active') === 'on' ? 1 : 0 }); setEditing(null); await load(); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  return <main className="page"><div className="page-heading"><div><p className="eyebrow">COMERCIAL</p><h1>Planes</h1></div></div><p>Catálogo comercial global. Los precios vienen de la base de datos; las capacidades se definen de forma segura en código.</p>{error && <p className="error" role="alert">{error}</p>}<div className="experience-list">{plans.map((plan) => { const definition = COMMERCIAL_PLAN_DEFINITIONS[plan.code as CommercialPlanCode]; return <article className="experience-card" key={plan.id}><div><h2>{plan.name}</h2><p>{definition?.description ?? plan.description}</p></div><span>{interval(plan)}</span><strong>{plan.pricingMode === 'free' ? 'Gratis' : price(plan)}</strong><span className={`status status-${plan.active && plan.availableForSale && plan.pricingMode !== 'unconfigured' ? 'active' : 'paused'}`}>{plan.active && plan.availableForSale && plan.pricingMode !== 'unconfigured' ? 'Disponible' : (plan.active ? 'No disponible' : 'Inactivo')}</span>{definition && <div><small>Incluye</small><ul>{definition.features.map((feature) => <li key={feature}>{COMMERCIAL_FEATURE_LABELS[feature]}</li>)}</ul><small>{definition.maxActiveExperiences === null ? 'Experiencias activas: sin límite definido' : `Experiencias activas: hasta ${definition.maxActiveExperiences}`}</small>{definition.serviceNotes.map((note) => <p key={note}><small>{note}</small></p>)}</div>}{canManageCatalog && (editing === plan.id ? <form onSubmit={(event) => { event.preventDefault(); void save(plan, event.currentTarget); }}><label>Nombre<input name="name" defaultValue={plan.name} /></label><label>Descripción<textarea name="description" defaultValue={plan.description ?? ''} /></label><label>Modalidad<select name="pricingMode" defaultValue={plan.pricingMode}><option value="unconfigured">Precio pendiente</option><option value="paid">Pagado</option><option value="free">Gratis</option></select></label><label>Precio<input name="amount" inputMode="decimal" defaultValue={plan.priceAmountMinor ? String(plan.priceAmountMinor / 100) : ''} placeholder="25000" disabled={plan.pricingMode === 'free'} /></label><label>Moneda<select name="currency" defaultValue={plan.currency}><option>ARS</option><option>USD</option></select></label><label><input type="checkbox" name="active" defaultChecked={plan.active === 1} /> Activo</label><label><input type="checkbox" name="available" defaultChecked={plan.availableForSale === 1} /> Disponible para venta</label><div className="modal-actions"><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancelar</button><button disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</button></div></form> : <button type="button" onClick={() => setEditing(plan.id)}>Editar precio y disponibilidad</button>)}</article>; })}</div></main>;
}
