import type React from 'react';
import { useEffect, useState } from 'react';
import { commercialApi, type Payment, type Plan, type Subscription } from '../api';

function displayDate(value: string) { return new Date(value).toLocaleString('es-AR'); }
export function SubscriptionsPage({ org, canManage }: { org: string; canManage: boolean }) {
  const [plans, setPlans] = useState<Plan[]>([]), [experiences, setExperiences] = useState<Array<{ id: string; name: string }>>([]), [items, setItems] = useState<Subscription[]>([]), [payments, setPayments] = useState<Record<string, Payment[]>>({}), [modal, setModal] = useState(false), [planId, setPlanId] = useState(''), [selected, setSelected] = useState<string[]>([]), [startsAt, setStartsAt] = useState(''), [error, setError] = useState(''), [saving, setSaving] = useState(false);
  async function load() { try { const [nextPlans, subscriptions, nextExperiences] = await Promise.all([commercialApi.plans(org), commercialApi.subscriptions(org), import('../../experiences/api').then(({ experiencesApi }) => experiencesApi.list(org))]); setPlans(nextPlans); setItems(subscriptions); setExperiences(nextExperiences); const paymentEntries = await Promise.all(subscriptions.map(async (item) => [item.id, await commercialApi.payments(item.id, org)] as const)); setPayments(Object.fromEntries(paymentEntries)); if (!planId) setPlanId(nextPlans[0]?.id ?? ''); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { if (org) void load(); }, [org]);
  async function create(e: React.FormEvent) { e.preventDefault(); if (!planId || !selected.length || !startsAt || saving) return; setSaving(true); setError(''); try { await commercialApi.createSubscription(org, { plan_id: planId, experience_ids: selected, starts_at: new Date(startsAt).toISOString() }); setModal(false); setSelected([]); setStartsAt(''); await load(); } catch (err) { setError((err as Error).message); } finally { setSaving(false); } }
  async function renew(item: Subscription) { setError(''); try { await commercialApi.renew(item.id, org, crypto.randomUUID()); await load(); } catch (e) { setError((e as Error).message); } }
  async function checkout(item: Subscription) { setError(''); try { const result = await commercialApi.checkout(item.id, org); window.location.assign(result.checkoutUrl); } catch (e) { setError((e as Error).message); } }
  async function cancel(item: Subscription) { if (!window.confirm('La suscripción seguirá vigente hasta el fin del período actual. ¿Cancelar renovación?')) return; try { await commercialApi.cancel(item.id, org); await load(); } catch (e) { setError((e as Error).message); } }
  return <main className="page"><div className="page-heading"><div><p className="eyebrow">COMERCIAL</p><h1>Suscripciones</h1></div>{canManage && <button onClick={() => { setError(''); setModal(true); }}>Nueva suscripción</button>}</div>{error && <p className="error" role="alert">{error}</p>}{items.length ? <div className="experience-list">{items.map((item) => <article className="experience-card" key={item.id}><div><h2>{item.planName}</h2><p>{item.experiences.map((experience) => experience.name).join(', ')}</p></div><span className={`status status-${item.effectiveStatus}`}>{item.effectiveStatus}</span><div><small>Período actual</small><br />{displayDate(item.currentPeriodStart)} → {displayDate(item.currentPeriodEnd)}</div>{canManage && <div className="modal-actions">{!item.cancelAtPeriodEnd && item.priceAmountMinor > 0 && <button type="button" onClick={() => void checkout(item)}>Generar pago</button>}{!item.cancelAtPeriodEnd && <button type="button" className="secondary" onClick={() => void renew(item)}>Renovación manual</button>}{!item.cancelAtPeriodEnd && <button type="button" className="secondary" onClick={() => void cancel(item)}>Cancelar al finalizar</button>}</div>} {!!payments[item.id]?.length && <div><small>Historial de pagos</small>{payments[item.id].map((payment) => <p key={payment.id}><small>{displayDate(payment.createdAt)} · {payment.provider} · {(payment.amountMinor / 100).toLocaleString('es-AR', { style: 'currency', currency: payment.currency })} · {payment.status}</small></p>)}</div>}</article>)}</div> : <div className="empty"><h2>No hay suscripciones.</h2>{canManage && <button onClick={() => setModal(true)}>Crear suscripción</button>}</div>}{modal && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><h2>Nueva suscripción</h2><form onSubmit={create}><label>Plan<select value={planId} onChange={(e) => setPlanId(e.target.value)}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label>Inicio<input type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} /></label><fieldset><legend>Experiencias</legend>{experiences.map((experience) => <label key={experience.id}><input type="checkbox" checked={selected.includes(experience.id)} onChange={(e) => setSelected((current) => e.target.checked ? [...current, experience.id] : current.filter((id) => id !== experience.id))} />{experience.name}</label>)}</fieldset><div className="modal-actions"><button type="button" className="secondary" onClick={() => setModal(false)}>Cancelar</button><button disabled={saving || !planId || !selected.length || !startsAt}>{saving ? 'Creando…' : 'Crear suscripción'}</button></div></form></div></div>}</main>;
}
